// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cmd/cmd_share_cd.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "cmd/cmd_share_cd.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace proto {
class ShareCDInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ShareCDInfo>
     _instance;
} _ShareCDInfo_default_instance_;
class AllShareCDDataNotify_ShareCdInfoMapEntryDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<AllShareCDDataNotify::AllShareCDDataNotify_ShareCdInfoMapEntry>
     _instance;
} _AllShareCDDataNotify_ShareCdInfoMapEntry_default_instance_;
class AllShareCDDataNotifyDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<AllShareCDDataNotify>
     _instance;
} _AllShareCDDataNotify_default_instance_;

namespace protobuf_cmd_2fcmd_5fshare_5fcd_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[3];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ShareCDInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ShareCDInfo, index_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ShareCDInfo, cd_start_time_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ShareCDInfo, share_cd_id_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AllShareCDDataNotify, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AllShareCDDataNotify, share_cd_info_map_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(ShareCDInfo)},
  { 8, -1, sizeof(AllShareCDDataNotify)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_ShareCDInfo_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_AllShareCDDataNotify_ShareCdInfoMapEntry_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_AllShareCDDataNotify_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "cmd/cmd_share_cd.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
file_level_metadata[1].reflection = AllShareCDDataNotify::AllShareCDDataNotify_ShareCdInfoMapEntry::CreateReflection(file_level_metadata[1].descriptor, _AllShareCDDataNotify_ShareCdInfoMapEntry_default_instance_._instance.get_mutable());
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::proto::protobuf_define_2eproto::InitDefaults();
  _ShareCDInfo_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_ShareCDInfo_default_instance_);_AllShareCDDataNotify_ShareCdInfoMapEntry_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_AllShareCDDataNotify_ShareCdInfoMapEntry_default_instance_);_AllShareCDDataNotify_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_AllShareCDDataNotify_default_instance_);_AllShareCDDataNotify_ShareCdInfoMapEntry_default_instance_._instance.get_mutable()->set_default_instance(_AllShareCDDataNotify_ShareCdInfoMapEntry_default_instance_._instance.get_mutable());
  _AllShareCDDataNotify_ShareCdInfoMapEntry_default_instance_._instance.get_mutable()->InitAsDefaultInstance();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\026cmd/cmd_share_cd.proto\022\005proto\032\014define."
      "proto\"H\n\013ShareCDInfo\022\r\n\005index\030\002 \001(\r\022\025\n\rc"
      "d_start_time\030\016 \001(\004\022\023\n\013share_cd_id\030\014 \001(\r\""
      "\255\001\n\024AllShareCDDataNotify\022J\n\021share_cd_inf"
      "o_map\030\002 \003(\0132/.proto.AllShareCDDataNotify"
      ".ShareCdInfoMapEntry\032I\n\023ShareCdInfoMapEn"
      "try\022\013\n\003key\030\001 \001(\r\022!\n\005value\030\002 \001(\0132\022.proto."
      "ShareCDInfo:\0028\001B(Z&github.com/teyvat-hel"
      "per/hk4e-proto/pbb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 345);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "cmd/cmd_share_cd.proto", &protobuf_RegisterTypes);
  ::proto::protobuf_define_2eproto::AddDescriptors();
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_cmd_2fcmd_5fshare_5fcd_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ShareCDInfo::kIndexFieldNumber;
const int ShareCDInfo::kCdStartTimeFieldNumber;
const int ShareCDInfo::kShareCdIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ShareCDInfo::ShareCDInfo()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_cmd_2fcmd_5fshare_5fcd_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.ShareCDInfo)
}
ShareCDInfo::ShareCDInfo(const ShareCDInfo& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&index_, &from.index_,
    static_cast<size_t>(reinterpret_cast<char*>(&cd_start_time_) -
    reinterpret_cast<char*>(&index_)) + sizeof(cd_start_time_));
  // @@protoc_insertion_point(copy_constructor:proto.ShareCDInfo)
}

void ShareCDInfo::SharedCtor() {
  ::memset(&index_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&cd_start_time_) -
      reinterpret_cast<char*>(&index_)) + sizeof(cd_start_time_));
  _cached_size_ = 0;
}

ShareCDInfo::~ShareCDInfo() {
  // @@protoc_insertion_point(destructor:proto.ShareCDInfo)
  SharedDtor();
}

void ShareCDInfo::SharedDtor() {
}

void ShareCDInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ShareCDInfo::descriptor() {
  protobuf_cmd_2fcmd_5fshare_5fcd_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cmd_2fcmd_5fshare_5fcd_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ShareCDInfo& ShareCDInfo::default_instance() {
  protobuf_cmd_2fcmd_5fshare_5fcd_2eproto::InitDefaults();
  return *internal_default_instance();
}

ShareCDInfo* ShareCDInfo::New(::google::protobuf::Arena* arena) const {
  ShareCDInfo* n = new ShareCDInfo;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ShareCDInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.ShareCDInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&index_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&cd_start_time_) -
      reinterpret_cast<char*>(&index_)) + sizeof(cd_start_time_));
  _internal_metadata_.Clear();
}

bool ShareCDInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto.ShareCDInfo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 index = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &index_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 share_cd_id = 12;
      case 12: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(96u /* 96 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &share_cd_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 cd_start_time = 14;
      case 14: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(112u /* 112 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &cd_start_time_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.ShareCDInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.ShareCDInfo)
  return false;
#undef DO_
}

void ShareCDInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.ShareCDInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 index = 2;
  if (this->index() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->index(), output);
  }

  // uint32 share_cd_id = 12;
  if (this->share_cd_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(12, this->share_cd_id(), output);
  }

  // uint64 cd_start_time = 14;
  if (this->cd_start_time() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(14, this->cd_start_time(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:proto.ShareCDInfo)
}

::google::protobuf::uint8* ShareCDInfo::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:proto.ShareCDInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 index = 2;
  if (this->index() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->index(), target);
  }

  // uint32 share_cd_id = 12;
  if (this->share_cd_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(12, this->share_cd_id(), target);
  }

  // uint64 cd_start_time = 14;
  if (this->cd_start_time() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(14, this->cd_start_time(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.ShareCDInfo)
  return target;
}

size_t ShareCDInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.ShareCDInfo)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // uint32 index = 2;
  if (this->index() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->index());
  }

  // uint32 share_cd_id = 12;
  if (this->share_cd_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->share_cd_id());
  }

  // uint64 cd_start_time = 14;
  if (this->cd_start_time() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->cd_start_time());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ShareCDInfo::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto.ShareCDInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const ShareCDInfo* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ShareCDInfo>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto.ShareCDInfo)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto.ShareCDInfo)
    MergeFrom(*source);
  }
}

void ShareCDInfo::MergeFrom(const ShareCDInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.ShareCDInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.index() != 0) {
    set_index(from.index());
  }
  if (from.share_cd_id() != 0) {
    set_share_cd_id(from.share_cd_id());
  }
  if (from.cd_start_time() != 0) {
    set_cd_start_time(from.cd_start_time());
  }
}

void ShareCDInfo::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto.ShareCDInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ShareCDInfo::CopyFrom(const ShareCDInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.ShareCDInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ShareCDInfo::IsInitialized() const {
  return true;
}

void ShareCDInfo::Swap(ShareCDInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ShareCDInfo::InternalSwap(ShareCDInfo* other) {
  using std::swap;
  swap(index_, other->index_);
  swap(share_cd_id_, other->share_cd_id_);
  swap(cd_start_time_, other->cd_start_time_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ShareCDInfo::GetMetadata() const {
  protobuf_cmd_2fcmd_5fshare_5fcd_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cmd_2fcmd_5fshare_5fcd_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ShareCDInfo

// uint32 index = 2;
void ShareCDInfo::clear_index() {
  index_ = 0u;
}
::google::protobuf::uint32 ShareCDInfo::index() const {
  // @@protoc_insertion_point(field_get:proto.ShareCDInfo.index)
  return index_;
}
void ShareCDInfo::set_index(::google::protobuf::uint32 value) {
  
  index_ = value;
  // @@protoc_insertion_point(field_set:proto.ShareCDInfo.index)
}

// uint64 cd_start_time = 14;
void ShareCDInfo::clear_cd_start_time() {
  cd_start_time_ = GOOGLE_ULONGLONG(0);
}
::google::protobuf::uint64 ShareCDInfo::cd_start_time() const {
  // @@protoc_insertion_point(field_get:proto.ShareCDInfo.cd_start_time)
  return cd_start_time_;
}
void ShareCDInfo::set_cd_start_time(::google::protobuf::uint64 value) {
  
  cd_start_time_ = value;
  // @@protoc_insertion_point(field_set:proto.ShareCDInfo.cd_start_time)
}

// uint32 share_cd_id = 12;
void ShareCDInfo::clear_share_cd_id() {
  share_cd_id_ = 0u;
}
::google::protobuf::uint32 ShareCDInfo::share_cd_id() const {
  // @@protoc_insertion_point(field_get:proto.ShareCDInfo.share_cd_id)
  return share_cd_id_;
}
void ShareCDInfo::set_share_cd_id(::google::protobuf::uint32 value) {
  
  share_cd_id_ = value;
  // @@protoc_insertion_point(field_set:proto.ShareCDInfo.share_cd_id)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

AllShareCDDataNotify::AllShareCDDataNotify_ShareCdInfoMapEntry::AllShareCDDataNotify_ShareCdInfoMapEntry() {}
AllShareCDDataNotify::AllShareCDDataNotify_ShareCdInfoMapEntry::AllShareCDDataNotify_ShareCdInfoMapEntry(::google::protobuf::Arena* arena) : SuperType(arena) {}
::google::protobuf::Metadata AllShareCDDataNotify::AllShareCDDataNotify_ShareCdInfoMapEntry::GetMetadata() const {
  protobuf_cmd_2fcmd_5fshare_5fcd_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cmd_2fcmd_5fshare_5fcd_2eproto::file_level_metadata[1];
}
void AllShareCDDataNotify::AllShareCDDataNotify_ShareCdInfoMapEntry::MergeFrom(
    const ::google::protobuf::Message& other) {
  ::google::protobuf::Message::MergeFrom(other);
}
void AllShareCDDataNotify::AllShareCDDataNotify_ShareCdInfoMapEntry::MergeFrom(const AllShareCDDataNotify_ShareCdInfoMapEntry& other) {
  MergeFromInternal(other);
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int AllShareCDDataNotify::kShareCdInfoMapFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

AllShareCDDataNotify::AllShareCDDataNotify()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_cmd_2fcmd_5fshare_5fcd_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.AllShareCDDataNotify)
}
AllShareCDDataNotify::AllShareCDDataNotify(const AllShareCDDataNotify& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  share_cd_info_map_.MergeFrom(from.share_cd_info_map_);
  // @@protoc_insertion_point(copy_constructor:proto.AllShareCDDataNotify)
}

void AllShareCDDataNotify::SharedCtor() {
  _cached_size_ = 0;
}

AllShareCDDataNotify::~AllShareCDDataNotify() {
  // @@protoc_insertion_point(destructor:proto.AllShareCDDataNotify)
  SharedDtor();
}

void AllShareCDDataNotify::SharedDtor() {
}

void AllShareCDDataNotify::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AllShareCDDataNotify::descriptor() {
  protobuf_cmd_2fcmd_5fshare_5fcd_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cmd_2fcmd_5fshare_5fcd_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const AllShareCDDataNotify& AllShareCDDataNotify::default_instance() {
  protobuf_cmd_2fcmd_5fshare_5fcd_2eproto::InitDefaults();
  return *internal_default_instance();
}

AllShareCDDataNotify* AllShareCDDataNotify::New(::google::protobuf::Arena* arena) const {
  AllShareCDDataNotify* n = new AllShareCDDataNotify;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void AllShareCDDataNotify::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.AllShareCDDataNotify)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  share_cd_info_map_.Clear();
  _internal_metadata_.Clear();
}

bool AllShareCDDataNotify::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto.AllShareCDDataNotify)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // map<uint32, .proto.ShareCDInfo> share_cd_info_map = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          AllShareCDDataNotify_ShareCdInfoMapEntry::Parser< ::google::protobuf::internal::MapField<
              AllShareCDDataNotify_ShareCdInfoMapEntry,
              ::google::protobuf::uint32, ::proto::ShareCDInfo,
              ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
              ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
              0 >,
            ::google::protobuf::Map< ::google::protobuf::uint32, ::proto::ShareCDInfo > > parser(&share_cd_info_map_);
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
              input, &parser));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.AllShareCDDataNotify)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.AllShareCDDataNotify)
  return false;
#undef DO_
}

void AllShareCDDataNotify::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.AllShareCDDataNotify)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // map<uint32, .proto.ShareCDInfo> share_cd_info_map = 2;
  if (!this->share_cd_info_map().empty()) {
    typedef ::google::protobuf::Map< ::google::protobuf::uint32, ::proto::ShareCDInfo >::const_pointer
        ConstPtr;
    typedef ::google::protobuf::internal::SortItem< ::google::protobuf::uint32, ConstPtr > SortItem;
    typedef ::google::protobuf::internal::CompareByFirstField<SortItem> Less;

    if (output->IsSerializationDeterministic() &&
        this->share_cd_info_map().size() > 1) {
      ::google::protobuf::scoped_array<SortItem> items(
          new SortItem[this->share_cd_info_map().size()]);
      typedef ::google::protobuf::Map< ::google::protobuf::uint32, ::proto::ShareCDInfo >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::google::protobuf::uint32, ::proto::ShareCDInfo >::const_iterator
          it = this->share_cd_info_map().begin();
          it != this->share_cd_info_map().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::google::protobuf::scoped_ptr<AllShareCDDataNotify_ShareCdInfoMapEntry> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(share_cd_info_map_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)].second->first, items[static_cast<ptrdiff_t>(i)].second->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            2, *entry, output);
      }
    } else {
      ::google::protobuf::scoped_ptr<AllShareCDDataNotify_ShareCdInfoMapEntry> entry;
      for (::google::protobuf::Map< ::google::protobuf::uint32, ::proto::ShareCDInfo >::const_iterator
          it = this->share_cd_info_map().begin();
          it != this->share_cd_info_map().end(); ++it) {
        entry.reset(share_cd_info_map_.NewEntryWrapper(
            it->first, it->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            2, *entry, output);
      }
    }
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:proto.AllShareCDDataNotify)
}

::google::protobuf::uint8* AllShareCDDataNotify::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:proto.AllShareCDDataNotify)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // map<uint32, .proto.ShareCDInfo> share_cd_info_map = 2;
  if (!this->share_cd_info_map().empty()) {
    typedef ::google::protobuf::Map< ::google::protobuf::uint32, ::proto::ShareCDInfo >::const_pointer
        ConstPtr;
    typedef ::google::protobuf::internal::SortItem< ::google::protobuf::uint32, ConstPtr > SortItem;
    typedef ::google::protobuf::internal::CompareByFirstField<SortItem> Less;

    if (deterministic &&
        this->share_cd_info_map().size() > 1) {
      ::google::protobuf::scoped_array<SortItem> items(
          new SortItem[this->share_cd_info_map().size()]);
      typedef ::google::protobuf::Map< ::google::protobuf::uint32, ::proto::ShareCDInfo >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::google::protobuf::uint32, ::proto::ShareCDInfo >::const_iterator
          it = this->share_cd_info_map().begin();
          it != this->share_cd_info_map().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::google::protobuf::scoped_ptr<AllShareCDDataNotify_ShareCdInfoMapEntry> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(share_cd_info_map_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)].second->first, items[static_cast<ptrdiff_t>(i)].second->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       2, *entry, deterministic, target);
;
      }
    } else {
      ::google::protobuf::scoped_ptr<AllShareCDDataNotify_ShareCdInfoMapEntry> entry;
      for (::google::protobuf::Map< ::google::protobuf::uint32, ::proto::ShareCDInfo >::const_iterator
          it = this->share_cd_info_map().begin();
          it != this->share_cd_info_map().end(); ++it) {
        entry.reset(share_cd_info_map_.NewEntryWrapper(
            it->first, it->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       2, *entry, deterministic, target);
;
      }
    }
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.AllShareCDDataNotify)
  return target;
}

size_t AllShareCDDataNotify::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.AllShareCDDataNotify)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // map<uint32, .proto.ShareCDInfo> share_cd_info_map = 2;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->share_cd_info_map_size());
  {
    ::google::protobuf::scoped_ptr<AllShareCDDataNotify_ShareCdInfoMapEntry> entry;
    for (::google::protobuf::Map< ::google::protobuf::uint32, ::proto::ShareCDInfo >::const_iterator
        it = this->share_cd_info_map().begin();
        it != this->share_cd_info_map().end(); ++it) {
      entry.reset(share_cd_info_map_.NewEntryWrapper(it->first, it->second));
      total_size += ::google::protobuf::internal::WireFormatLite::
          MessageSizeNoVirtual(*entry);
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AllShareCDDataNotify::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto.AllShareCDDataNotify)
  GOOGLE_DCHECK_NE(&from, this);
  const AllShareCDDataNotify* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const AllShareCDDataNotify>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto.AllShareCDDataNotify)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto.AllShareCDDataNotify)
    MergeFrom(*source);
  }
}

void AllShareCDDataNotify::MergeFrom(const AllShareCDDataNotify& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.AllShareCDDataNotify)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  share_cd_info_map_.MergeFrom(from.share_cd_info_map_);
}

void AllShareCDDataNotify::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto.AllShareCDDataNotify)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AllShareCDDataNotify::CopyFrom(const AllShareCDDataNotify& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.AllShareCDDataNotify)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AllShareCDDataNotify::IsInitialized() const {
  return true;
}

void AllShareCDDataNotify::Swap(AllShareCDDataNotify* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AllShareCDDataNotify::InternalSwap(AllShareCDDataNotify* other) {
  using std::swap;
  share_cd_info_map_.Swap(&other->share_cd_info_map_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata AllShareCDDataNotify::GetMetadata() const {
  protobuf_cmd_2fcmd_5fshare_5fcd_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cmd_2fcmd_5fshare_5fcd_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// AllShareCDDataNotify

// map<uint32, .proto.ShareCDInfo> share_cd_info_map = 2;
int AllShareCDDataNotify::share_cd_info_map_size() const {
  return share_cd_info_map_.size();
}
void AllShareCDDataNotify::clear_share_cd_info_map() {
  share_cd_info_map_.Clear();
}
 const ::google::protobuf::Map< ::google::protobuf::uint32, ::proto::ShareCDInfo >&
AllShareCDDataNotify::share_cd_info_map() const {
  // @@protoc_insertion_point(field_map:proto.AllShareCDDataNotify.share_cd_info_map)
  return share_cd_info_map_.GetMap();
}
 ::google::protobuf::Map< ::google::protobuf::uint32, ::proto::ShareCDInfo >*
AllShareCDDataNotify::mutable_share_cd_info_map() {
  // @@protoc_insertion_point(field_mutable_map:proto.AllShareCDDataNotify.share_cd_info_map)
  return share_cd_info_map_.MutableMap();
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto

// @@protoc_insertion_point(global_scope)
