// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cmd/cmd_aranara_collection.proto

#ifndef PROTOBUF_cmd_2fcmd_5faranara_5fcollection_2eproto__INCLUDED
#define PROTOBUF_cmd_2fcmd_5faranara_5fcollection_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
#include "define.pb.h"
// @@protoc_insertion_point(includes)
namespace proto {
class AddAranaraCollectionNotify;
class AddAranaraCollectionNotifyDefaultTypeInternal;
extern AddAranaraCollectionNotifyDefaultTypeInternal _AddAranaraCollectionNotify_default_instance_;
class AranaraCollectionDataNotify;
class AranaraCollectionDataNotifyDefaultTypeInternal;
extern AranaraCollectionDataNotifyDefaultTypeInternal _AranaraCollectionDataNotify_default_instance_;
class AranaraCollectionSuite;
class AranaraCollectionSuiteDefaultTypeInternal;
extern AranaraCollectionSuiteDefaultTypeInternal _AranaraCollectionSuite_default_instance_;
class AranaraCollectionSuite_CollectionIdStateMapEntry;
class AranaraCollectionSuite_CollectionIdStateMapEntryDefaultTypeInternal;
extern AranaraCollectionSuite_CollectionIdStateMapEntryDefaultTypeInternal _AranaraCollectionSuite_CollectionIdStateMapEntry_default_instance_;
class CataLogFinishedGlobalWatcherAllDataNotify;
class CataLogFinishedGlobalWatcherAllDataNotifyDefaultTypeInternal;
extern CataLogFinishedGlobalWatcherAllDataNotifyDefaultTypeInternal _CataLogFinishedGlobalWatcherAllDataNotify_default_instance_;
class CataLogGlobalWatcherFinishedData;
class CataLogGlobalWatcherFinishedDataDefaultTypeInternal;
extern CataLogGlobalWatcherFinishedDataDefaultTypeInternal _CataLogGlobalWatcherFinishedData_default_instance_;
class CataLogNewFinishedGlobalWatcherNotify;
class CataLogNewFinishedGlobalWatcherNotifyDefaultTypeInternal;
extern CataLogNewFinishedGlobalWatcherNotifyDefaultTypeInternal _CataLogNewFinishedGlobalWatcherNotify_default_instance_;
}  // namespace proto

namespace proto {

namespace protobuf_cmd_2fcmd_5faranara_5fcollection_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_cmd_2fcmd_5faranara_5fcollection_2eproto

// ===================================================================


// -------------------------------------------------------------------

class AranaraCollectionSuite : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.AranaraCollectionSuite) */ {
 public:
  AranaraCollectionSuite();
  virtual ~AranaraCollectionSuite();

  AranaraCollectionSuite(const AranaraCollectionSuite& from);

  inline AranaraCollectionSuite& operator=(const AranaraCollectionSuite& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AranaraCollectionSuite(AranaraCollectionSuite&& from) noexcept
    : AranaraCollectionSuite() {
    *this = ::std::move(from);
  }

  inline AranaraCollectionSuite& operator=(AranaraCollectionSuite&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const AranaraCollectionSuite& default_instance();

  static inline const AranaraCollectionSuite* internal_default_instance() {
    return reinterpret_cast<const AranaraCollectionSuite*>(
               &_AranaraCollectionSuite_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(AranaraCollectionSuite* other);
  friend void swap(AranaraCollectionSuite& a, AranaraCollectionSuite& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AranaraCollectionSuite* New() const PROTOBUF_FINAL { return New(NULL); }

  AranaraCollectionSuite* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AranaraCollectionSuite& from);
  void MergeFrom(const AranaraCollectionSuite& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AranaraCollectionSuite* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<uint32, .proto.AranaraCollectionState> collection_id_state_map = 6;
  int collection_id_state_map_size() const;
  void clear_collection_id_state_map();
  static const int kCollectionIdStateMapFieldNumber = 6;
  const ::google::protobuf::Map< ::google::protobuf::uint32, ::proto::AranaraCollectionState >&
      collection_id_state_map() const;
  ::google::protobuf::Map< ::google::protobuf::uint32, ::proto::AranaraCollectionState >*
      mutable_collection_id_state_map();

  // uint32 collection_type = 12;
  void clear_collection_type();
  static const int kCollectionTypeFieldNumber = 12;
  ::google::protobuf::uint32 collection_type() const;
  void set_collection_type(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.AranaraCollectionSuite)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  public:
  class AranaraCollectionSuite_CollectionIdStateMapEntry : public ::google::protobuf::internal::MapEntry<AranaraCollectionSuite_CollectionIdStateMapEntry, 
      ::google::protobuf::uint32, ::proto::AranaraCollectionState,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_ENUM,
      0 > {
  public:
    typedef ::google::protobuf::internal::MapEntry<AranaraCollectionSuite_CollectionIdStateMapEntry, 
      ::google::protobuf::uint32, ::proto::AranaraCollectionState,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_ENUM,
      0 > SuperType;
    AranaraCollectionSuite_CollectionIdStateMapEntry();
    AranaraCollectionSuite_CollectionIdStateMapEntry(::google::protobuf::Arena* arena);
    void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
    void MergeFrom(const AranaraCollectionSuite_CollectionIdStateMapEntry& other);
    static const Message* internal_default_instance() { return reinterpret_cast<const Message*>(&_AranaraCollectionSuite_CollectionIdStateMapEntry_default_instance_); }
    ::google::protobuf::Metadata GetMetadata() const;
  };
  private:
  ::google::protobuf::internal::MapField<
      AranaraCollectionSuite_CollectionIdStateMapEntry,
      ::google::protobuf::uint32, ::proto::AranaraCollectionState,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_ENUM,
      0 > collection_id_state_map_;
  private:
  ::google::protobuf::uint32 collection_type_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5faranara_5fcollection_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class AranaraCollectionDataNotify : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.AranaraCollectionDataNotify) */ {
 public:
  AranaraCollectionDataNotify();
  virtual ~AranaraCollectionDataNotify();

  AranaraCollectionDataNotify(const AranaraCollectionDataNotify& from);

  inline AranaraCollectionDataNotify& operator=(const AranaraCollectionDataNotify& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AranaraCollectionDataNotify(AranaraCollectionDataNotify&& from) noexcept
    : AranaraCollectionDataNotify() {
    *this = ::std::move(from);
  }

  inline AranaraCollectionDataNotify& operator=(AranaraCollectionDataNotify&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const AranaraCollectionDataNotify& default_instance();

  static inline const AranaraCollectionDataNotify* internal_default_instance() {
    return reinterpret_cast<const AranaraCollectionDataNotify*>(
               &_AranaraCollectionDataNotify_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(AranaraCollectionDataNotify* other);
  friend void swap(AranaraCollectionDataNotify& a, AranaraCollectionDataNotify& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AranaraCollectionDataNotify* New() const PROTOBUF_FINAL { return New(NULL); }

  AranaraCollectionDataNotify* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AranaraCollectionDataNotify& from);
  void MergeFrom(const AranaraCollectionDataNotify& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AranaraCollectionDataNotify* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .proto.AranaraCollectionSuite collection_suite_list = 14;
  int collection_suite_list_size() const;
  void clear_collection_suite_list();
  static const int kCollectionSuiteListFieldNumber = 14;
  const ::proto::AranaraCollectionSuite& collection_suite_list(int index) const;
  ::proto::AranaraCollectionSuite* mutable_collection_suite_list(int index);
  ::proto::AranaraCollectionSuite* add_collection_suite_list();
  ::google::protobuf::RepeatedPtrField< ::proto::AranaraCollectionSuite >*
      mutable_collection_suite_list();
  const ::google::protobuf::RepeatedPtrField< ::proto::AranaraCollectionSuite >&
      collection_suite_list() const;

  // @@protoc_insertion_point(class_scope:proto.AranaraCollectionDataNotify)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::proto::AranaraCollectionSuite > collection_suite_list_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5faranara_5fcollection_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class AddAranaraCollectionNotify : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.AddAranaraCollectionNotify) */ {
 public:
  AddAranaraCollectionNotify();
  virtual ~AddAranaraCollectionNotify();

  AddAranaraCollectionNotify(const AddAranaraCollectionNotify& from);

  inline AddAranaraCollectionNotify& operator=(const AddAranaraCollectionNotify& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AddAranaraCollectionNotify(AddAranaraCollectionNotify&& from) noexcept
    : AddAranaraCollectionNotify() {
    *this = ::std::move(from);
  }

  inline AddAranaraCollectionNotify& operator=(AddAranaraCollectionNotify&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const AddAranaraCollectionNotify& default_instance();

  static inline const AddAranaraCollectionNotify* internal_default_instance() {
    return reinterpret_cast<const AddAranaraCollectionNotify*>(
               &_AddAranaraCollectionNotify_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(AddAranaraCollectionNotify* other);
  friend void swap(AddAranaraCollectionNotify& a, AddAranaraCollectionNotify& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AddAranaraCollectionNotify* New() const PROTOBUF_FINAL { return New(NULL); }

  AddAranaraCollectionNotify* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AddAranaraCollectionNotify& from);
  void MergeFrom(const AddAranaraCollectionNotify& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AddAranaraCollectionNotify* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 collection_type = 7;
  void clear_collection_type();
  static const int kCollectionTypeFieldNumber = 7;
  ::google::protobuf::uint32 collection_type() const;
  void set_collection_type(::google::protobuf::uint32 value);

  // uint32 collection_id = 8;
  void clear_collection_id();
  static const int kCollectionIdFieldNumber = 8;
  ::google::protobuf::uint32 collection_id() const;
  void set_collection_id(::google::protobuf::uint32 value);

  // .proto.AranaraCollectionState target_state = 12;
  void clear_target_state();
  static const int kTargetStateFieldNumber = 12;
  ::proto::AranaraCollectionState target_state() const;
  void set_target_state(::proto::AranaraCollectionState value);

  // .proto.AranaraCollectionState from_state = 15;
  void clear_from_state();
  static const int kFromStateFieldNumber = 15;
  ::proto::AranaraCollectionState from_state() const;
  void set_from_state(::proto::AranaraCollectionState value);

  // @@protoc_insertion_point(class_scope:proto.AddAranaraCollectionNotify)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 collection_type_;
  ::google::protobuf::uint32 collection_id_;
  int target_state_;
  int from_state_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5faranara_5fcollection_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CataLogGlobalWatcherFinishedData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.CataLogGlobalWatcherFinishedData) */ {
 public:
  CataLogGlobalWatcherFinishedData();
  virtual ~CataLogGlobalWatcherFinishedData();

  CataLogGlobalWatcherFinishedData(const CataLogGlobalWatcherFinishedData& from);

  inline CataLogGlobalWatcherFinishedData& operator=(const CataLogGlobalWatcherFinishedData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CataLogGlobalWatcherFinishedData(CataLogGlobalWatcherFinishedData&& from) noexcept
    : CataLogGlobalWatcherFinishedData() {
    *this = ::std::move(from);
  }

  inline CataLogGlobalWatcherFinishedData& operator=(CataLogGlobalWatcherFinishedData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const CataLogGlobalWatcherFinishedData& default_instance();

  static inline const CataLogGlobalWatcherFinishedData* internal_default_instance() {
    return reinterpret_cast<const CataLogGlobalWatcherFinishedData*>(
               &_CataLogGlobalWatcherFinishedData_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(CataLogGlobalWatcherFinishedData* other);
  friend void swap(CataLogGlobalWatcherFinishedData& a, CataLogGlobalWatcherFinishedData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CataLogGlobalWatcherFinishedData* New() const PROTOBUF_FINAL { return New(NULL); }

  CataLogGlobalWatcherFinishedData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CataLogGlobalWatcherFinishedData& from);
  void MergeFrom(const CataLogGlobalWatcherFinishedData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CataLogGlobalWatcherFinishedData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 finished_global_watcher_list = 8;
  int finished_global_watcher_list_size() const;
  void clear_finished_global_watcher_list();
  static const int kFinishedGlobalWatcherListFieldNumber = 8;
  ::google::protobuf::uint32 finished_global_watcher_list(int index) const;
  void set_finished_global_watcher_list(int index, ::google::protobuf::uint32 value);
  void add_finished_global_watcher_list(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      finished_global_watcher_list() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_finished_global_watcher_list();

  // uint32 catalog_type = 13;
  void clear_catalog_type();
  static const int kCatalogTypeFieldNumber = 13;
  ::google::protobuf::uint32 catalog_type() const;
  void set_catalog_type(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.CataLogGlobalWatcherFinishedData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > finished_global_watcher_list_;
  mutable int _finished_global_watcher_list_cached_byte_size_;
  ::google::protobuf::uint32 catalog_type_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5faranara_5fcollection_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CataLogFinishedGlobalWatcherAllDataNotify : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.CataLogFinishedGlobalWatcherAllDataNotify) */ {
 public:
  CataLogFinishedGlobalWatcherAllDataNotify();
  virtual ~CataLogFinishedGlobalWatcherAllDataNotify();

  CataLogFinishedGlobalWatcherAllDataNotify(const CataLogFinishedGlobalWatcherAllDataNotify& from);

  inline CataLogFinishedGlobalWatcherAllDataNotify& operator=(const CataLogFinishedGlobalWatcherAllDataNotify& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CataLogFinishedGlobalWatcherAllDataNotify(CataLogFinishedGlobalWatcherAllDataNotify&& from) noexcept
    : CataLogFinishedGlobalWatcherAllDataNotify() {
    *this = ::std::move(from);
  }

  inline CataLogFinishedGlobalWatcherAllDataNotify& operator=(CataLogFinishedGlobalWatcherAllDataNotify&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const CataLogFinishedGlobalWatcherAllDataNotify& default_instance();

  static inline const CataLogFinishedGlobalWatcherAllDataNotify* internal_default_instance() {
    return reinterpret_cast<const CataLogFinishedGlobalWatcherAllDataNotify*>(
               &_CataLogFinishedGlobalWatcherAllDataNotify_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(CataLogFinishedGlobalWatcherAllDataNotify* other);
  friend void swap(CataLogFinishedGlobalWatcherAllDataNotify& a, CataLogFinishedGlobalWatcherAllDataNotify& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CataLogFinishedGlobalWatcherAllDataNotify* New() const PROTOBUF_FINAL { return New(NULL); }

  CataLogFinishedGlobalWatcherAllDataNotify* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CataLogFinishedGlobalWatcherAllDataNotify& from);
  void MergeFrom(const CataLogFinishedGlobalWatcherAllDataNotify& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CataLogFinishedGlobalWatcherAllDataNotify* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .proto.CataLogGlobalWatcherFinishedData finished_global_watcher_data_list = 13;
  int finished_global_watcher_data_list_size() const;
  void clear_finished_global_watcher_data_list();
  static const int kFinishedGlobalWatcherDataListFieldNumber = 13;
  const ::proto::CataLogGlobalWatcherFinishedData& finished_global_watcher_data_list(int index) const;
  ::proto::CataLogGlobalWatcherFinishedData* mutable_finished_global_watcher_data_list(int index);
  ::proto::CataLogGlobalWatcherFinishedData* add_finished_global_watcher_data_list();
  ::google::protobuf::RepeatedPtrField< ::proto::CataLogGlobalWatcherFinishedData >*
      mutable_finished_global_watcher_data_list();
  const ::google::protobuf::RepeatedPtrField< ::proto::CataLogGlobalWatcherFinishedData >&
      finished_global_watcher_data_list() const;

  // @@protoc_insertion_point(class_scope:proto.CataLogFinishedGlobalWatcherAllDataNotify)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::proto::CataLogGlobalWatcherFinishedData > finished_global_watcher_data_list_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5faranara_5fcollection_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CataLogNewFinishedGlobalWatcherNotify : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.CataLogNewFinishedGlobalWatcherNotify) */ {
 public:
  CataLogNewFinishedGlobalWatcherNotify();
  virtual ~CataLogNewFinishedGlobalWatcherNotify();

  CataLogNewFinishedGlobalWatcherNotify(const CataLogNewFinishedGlobalWatcherNotify& from);

  inline CataLogNewFinishedGlobalWatcherNotify& operator=(const CataLogNewFinishedGlobalWatcherNotify& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CataLogNewFinishedGlobalWatcherNotify(CataLogNewFinishedGlobalWatcherNotify&& from) noexcept
    : CataLogNewFinishedGlobalWatcherNotify() {
    *this = ::std::move(from);
  }

  inline CataLogNewFinishedGlobalWatcherNotify& operator=(CataLogNewFinishedGlobalWatcherNotify&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const CataLogNewFinishedGlobalWatcherNotify& default_instance();

  static inline const CataLogNewFinishedGlobalWatcherNotify* internal_default_instance() {
    return reinterpret_cast<const CataLogNewFinishedGlobalWatcherNotify*>(
               &_CataLogNewFinishedGlobalWatcherNotify_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(CataLogNewFinishedGlobalWatcherNotify* other);
  friend void swap(CataLogNewFinishedGlobalWatcherNotify& a, CataLogNewFinishedGlobalWatcherNotify& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CataLogNewFinishedGlobalWatcherNotify* New() const PROTOBUF_FINAL { return New(NULL); }

  CataLogNewFinishedGlobalWatcherNotify* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CataLogNewFinishedGlobalWatcherNotify& from);
  void MergeFrom(const CataLogNewFinishedGlobalWatcherNotify& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CataLogNewFinishedGlobalWatcherNotify* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .proto.CataLogGlobalWatcherFinishedData new_finished_global_watcher_data_list = 2;
  int new_finished_global_watcher_data_list_size() const;
  void clear_new_finished_global_watcher_data_list();
  static const int kNewFinishedGlobalWatcherDataListFieldNumber = 2;
  const ::proto::CataLogGlobalWatcherFinishedData& new_finished_global_watcher_data_list(int index) const;
  ::proto::CataLogGlobalWatcherFinishedData* mutable_new_finished_global_watcher_data_list(int index);
  ::proto::CataLogGlobalWatcherFinishedData* add_new_finished_global_watcher_data_list();
  ::google::protobuf::RepeatedPtrField< ::proto::CataLogGlobalWatcherFinishedData >*
      mutable_new_finished_global_watcher_data_list();
  const ::google::protobuf::RepeatedPtrField< ::proto::CataLogGlobalWatcherFinishedData >&
      new_finished_global_watcher_data_list() const;

  // @@protoc_insertion_point(class_scope:proto.CataLogNewFinishedGlobalWatcherNotify)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::proto::CataLogGlobalWatcherFinishedData > new_finished_global_watcher_data_list_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5faranara_5fcollection_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// AranaraCollectionSuite

// map<uint32, .proto.AranaraCollectionState> collection_id_state_map = 6;
inline int AranaraCollectionSuite::collection_id_state_map_size() const {
  return collection_id_state_map_.size();
}
inline void AranaraCollectionSuite::clear_collection_id_state_map() {
  collection_id_state_map_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::uint32, ::proto::AranaraCollectionState >&
AranaraCollectionSuite::collection_id_state_map() const {
  // @@protoc_insertion_point(field_map:proto.AranaraCollectionSuite.collection_id_state_map)
  return collection_id_state_map_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::uint32, ::proto::AranaraCollectionState >*
AranaraCollectionSuite::mutable_collection_id_state_map() {
  // @@protoc_insertion_point(field_mutable_map:proto.AranaraCollectionSuite.collection_id_state_map)
  return collection_id_state_map_.MutableMap();
}

// uint32 collection_type = 12;
inline void AranaraCollectionSuite::clear_collection_type() {
  collection_type_ = 0u;
}
inline ::google::protobuf::uint32 AranaraCollectionSuite::collection_type() const {
  // @@protoc_insertion_point(field_get:proto.AranaraCollectionSuite.collection_type)
  return collection_type_;
}
inline void AranaraCollectionSuite::set_collection_type(::google::protobuf::uint32 value) {
  
  collection_type_ = value;
  // @@protoc_insertion_point(field_set:proto.AranaraCollectionSuite.collection_type)
}

// -------------------------------------------------------------------

// AranaraCollectionDataNotify

// repeated .proto.AranaraCollectionSuite collection_suite_list = 14;
inline int AranaraCollectionDataNotify::collection_suite_list_size() const {
  return collection_suite_list_.size();
}
inline void AranaraCollectionDataNotify::clear_collection_suite_list() {
  collection_suite_list_.Clear();
}
inline const ::proto::AranaraCollectionSuite& AranaraCollectionDataNotify::collection_suite_list(int index) const {
  // @@protoc_insertion_point(field_get:proto.AranaraCollectionDataNotify.collection_suite_list)
  return collection_suite_list_.Get(index);
}
inline ::proto::AranaraCollectionSuite* AranaraCollectionDataNotify::mutable_collection_suite_list(int index) {
  // @@protoc_insertion_point(field_mutable:proto.AranaraCollectionDataNotify.collection_suite_list)
  return collection_suite_list_.Mutable(index);
}
inline ::proto::AranaraCollectionSuite* AranaraCollectionDataNotify::add_collection_suite_list() {
  // @@protoc_insertion_point(field_add:proto.AranaraCollectionDataNotify.collection_suite_list)
  return collection_suite_list_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::proto::AranaraCollectionSuite >*
AranaraCollectionDataNotify::mutable_collection_suite_list() {
  // @@protoc_insertion_point(field_mutable_list:proto.AranaraCollectionDataNotify.collection_suite_list)
  return &collection_suite_list_;
}
inline const ::google::protobuf::RepeatedPtrField< ::proto::AranaraCollectionSuite >&
AranaraCollectionDataNotify::collection_suite_list() const {
  // @@protoc_insertion_point(field_list:proto.AranaraCollectionDataNotify.collection_suite_list)
  return collection_suite_list_;
}

// -------------------------------------------------------------------

// AddAranaraCollectionNotify

// uint32 collection_type = 7;
inline void AddAranaraCollectionNotify::clear_collection_type() {
  collection_type_ = 0u;
}
inline ::google::protobuf::uint32 AddAranaraCollectionNotify::collection_type() const {
  // @@protoc_insertion_point(field_get:proto.AddAranaraCollectionNotify.collection_type)
  return collection_type_;
}
inline void AddAranaraCollectionNotify::set_collection_type(::google::protobuf::uint32 value) {
  
  collection_type_ = value;
  // @@protoc_insertion_point(field_set:proto.AddAranaraCollectionNotify.collection_type)
}

// .proto.AranaraCollectionState target_state = 12;
inline void AddAranaraCollectionNotify::clear_target_state() {
  target_state_ = 0;
}
inline ::proto::AranaraCollectionState AddAranaraCollectionNotify::target_state() const {
  // @@protoc_insertion_point(field_get:proto.AddAranaraCollectionNotify.target_state)
  return static_cast< ::proto::AranaraCollectionState >(target_state_);
}
inline void AddAranaraCollectionNotify::set_target_state(::proto::AranaraCollectionState value) {
  
  target_state_ = value;
  // @@protoc_insertion_point(field_set:proto.AddAranaraCollectionNotify.target_state)
}

// .proto.AranaraCollectionState from_state = 15;
inline void AddAranaraCollectionNotify::clear_from_state() {
  from_state_ = 0;
}
inline ::proto::AranaraCollectionState AddAranaraCollectionNotify::from_state() const {
  // @@protoc_insertion_point(field_get:proto.AddAranaraCollectionNotify.from_state)
  return static_cast< ::proto::AranaraCollectionState >(from_state_);
}
inline void AddAranaraCollectionNotify::set_from_state(::proto::AranaraCollectionState value) {
  
  from_state_ = value;
  // @@protoc_insertion_point(field_set:proto.AddAranaraCollectionNotify.from_state)
}

// uint32 collection_id = 8;
inline void AddAranaraCollectionNotify::clear_collection_id() {
  collection_id_ = 0u;
}
inline ::google::protobuf::uint32 AddAranaraCollectionNotify::collection_id() const {
  // @@protoc_insertion_point(field_get:proto.AddAranaraCollectionNotify.collection_id)
  return collection_id_;
}
inline void AddAranaraCollectionNotify::set_collection_id(::google::protobuf::uint32 value) {
  
  collection_id_ = value;
  // @@protoc_insertion_point(field_set:proto.AddAranaraCollectionNotify.collection_id)
}

// -------------------------------------------------------------------

// CataLogGlobalWatcherFinishedData

// repeated uint32 finished_global_watcher_list = 8;
inline int CataLogGlobalWatcherFinishedData::finished_global_watcher_list_size() const {
  return finished_global_watcher_list_.size();
}
inline void CataLogGlobalWatcherFinishedData::clear_finished_global_watcher_list() {
  finished_global_watcher_list_.Clear();
}
inline ::google::protobuf::uint32 CataLogGlobalWatcherFinishedData::finished_global_watcher_list(int index) const {
  // @@protoc_insertion_point(field_get:proto.CataLogGlobalWatcherFinishedData.finished_global_watcher_list)
  return finished_global_watcher_list_.Get(index);
}
inline void CataLogGlobalWatcherFinishedData::set_finished_global_watcher_list(int index, ::google::protobuf::uint32 value) {
  finished_global_watcher_list_.Set(index, value);
  // @@protoc_insertion_point(field_set:proto.CataLogGlobalWatcherFinishedData.finished_global_watcher_list)
}
inline void CataLogGlobalWatcherFinishedData::add_finished_global_watcher_list(::google::protobuf::uint32 value) {
  finished_global_watcher_list_.Add(value);
  // @@protoc_insertion_point(field_add:proto.CataLogGlobalWatcherFinishedData.finished_global_watcher_list)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
CataLogGlobalWatcherFinishedData::finished_global_watcher_list() const {
  // @@protoc_insertion_point(field_list:proto.CataLogGlobalWatcherFinishedData.finished_global_watcher_list)
  return finished_global_watcher_list_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
CataLogGlobalWatcherFinishedData::mutable_finished_global_watcher_list() {
  // @@protoc_insertion_point(field_mutable_list:proto.CataLogGlobalWatcherFinishedData.finished_global_watcher_list)
  return &finished_global_watcher_list_;
}

// uint32 catalog_type = 13;
inline void CataLogGlobalWatcherFinishedData::clear_catalog_type() {
  catalog_type_ = 0u;
}
inline ::google::protobuf::uint32 CataLogGlobalWatcherFinishedData::catalog_type() const {
  // @@protoc_insertion_point(field_get:proto.CataLogGlobalWatcherFinishedData.catalog_type)
  return catalog_type_;
}
inline void CataLogGlobalWatcherFinishedData::set_catalog_type(::google::protobuf::uint32 value) {
  
  catalog_type_ = value;
  // @@protoc_insertion_point(field_set:proto.CataLogGlobalWatcherFinishedData.catalog_type)
}

// -------------------------------------------------------------------

// CataLogFinishedGlobalWatcherAllDataNotify

// repeated .proto.CataLogGlobalWatcherFinishedData finished_global_watcher_data_list = 13;
inline int CataLogFinishedGlobalWatcherAllDataNotify::finished_global_watcher_data_list_size() const {
  return finished_global_watcher_data_list_.size();
}
inline void CataLogFinishedGlobalWatcherAllDataNotify::clear_finished_global_watcher_data_list() {
  finished_global_watcher_data_list_.Clear();
}
inline const ::proto::CataLogGlobalWatcherFinishedData& CataLogFinishedGlobalWatcherAllDataNotify::finished_global_watcher_data_list(int index) const {
  // @@protoc_insertion_point(field_get:proto.CataLogFinishedGlobalWatcherAllDataNotify.finished_global_watcher_data_list)
  return finished_global_watcher_data_list_.Get(index);
}
inline ::proto::CataLogGlobalWatcherFinishedData* CataLogFinishedGlobalWatcherAllDataNotify::mutable_finished_global_watcher_data_list(int index) {
  // @@protoc_insertion_point(field_mutable:proto.CataLogFinishedGlobalWatcherAllDataNotify.finished_global_watcher_data_list)
  return finished_global_watcher_data_list_.Mutable(index);
}
inline ::proto::CataLogGlobalWatcherFinishedData* CataLogFinishedGlobalWatcherAllDataNotify::add_finished_global_watcher_data_list() {
  // @@protoc_insertion_point(field_add:proto.CataLogFinishedGlobalWatcherAllDataNotify.finished_global_watcher_data_list)
  return finished_global_watcher_data_list_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::proto::CataLogGlobalWatcherFinishedData >*
CataLogFinishedGlobalWatcherAllDataNotify::mutable_finished_global_watcher_data_list() {
  // @@protoc_insertion_point(field_mutable_list:proto.CataLogFinishedGlobalWatcherAllDataNotify.finished_global_watcher_data_list)
  return &finished_global_watcher_data_list_;
}
inline const ::google::protobuf::RepeatedPtrField< ::proto::CataLogGlobalWatcherFinishedData >&
CataLogFinishedGlobalWatcherAllDataNotify::finished_global_watcher_data_list() const {
  // @@protoc_insertion_point(field_list:proto.CataLogFinishedGlobalWatcherAllDataNotify.finished_global_watcher_data_list)
  return finished_global_watcher_data_list_;
}

// -------------------------------------------------------------------

// CataLogNewFinishedGlobalWatcherNotify

// repeated .proto.CataLogGlobalWatcherFinishedData new_finished_global_watcher_data_list = 2;
inline int CataLogNewFinishedGlobalWatcherNotify::new_finished_global_watcher_data_list_size() const {
  return new_finished_global_watcher_data_list_.size();
}
inline void CataLogNewFinishedGlobalWatcherNotify::clear_new_finished_global_watcher_data_list() {
  new_finished_global_watcher_data_list_.Clear();
}
inline const ::proto::CataLogGlobalWatcherFinishedData& CataLogNewFinishedGlobalWatcherNotify::new_finished_global_watcher_data_list(int index) const {
  // @@protoc_insertion_point(field_get:proto.CataLogNewFinishedGlobalWatcherNotify.new_finished_global_watcher_data_list)
  return new_finished_global_watcher_data_list_.Get(index);
}
inline ::proto::CataLogGlobalWatcherFinishedData* CataLogNewFinishedGlobalWatcherNotify::mutable_new_finished_global_watcher_data_list(int index) {
  // @@protoc_insertion_point(field_mutable:proto.CataLogNewFinishedGlobalWatcherNotify.new_finished_global_watcher_data_list)
  return new_finished_global_watcher_data_list_.Mutable(index);
}
inline ::proto::CataLogGlobalWatcherFinishedData* CataLogNewFinishedGlobalWatcherNotify::add_new_finished_global_watcher_data_list() {
  // @@protoc_insertion_point(field_add:proto.CataLogNewFinishedGlobalWatcherNotify.new_finished_global_watcher_data_list)
  return new_finished_global_watcher_data_list_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::proto::CataLogGlobalWatcherFinishedData >*
CataLogNewFinishedGlobalWatcherNotify::mutable_new_finished_global_watcher_data_list() {
  // @@protoc_insertion_point(field_mutable_list:proto.CataLogNewFinishedGlobalWatcherNotify.new_finished_global_watcher_data_list)
  return &new_finished_global_watcher_data_list_;
}
inline const ::google::protobuf::RepeatedPtrField< ::proto::CataLogGlobalWatcherFinishedData >&
CataLogNewFinishedGlobalWatcherNotify::new_finished_global_watcher_data_list() const {
  // @@protoc_insertion_point(field_list:proto.CataLogNewFinishedGlobalWatcherNotify.new_finished_global_watcher_data_list)
  return new_finished_global_watcher_data_list_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace proto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cmd_2fcmd_5faranara_5fcollection_2eproto__INCLUDED
